import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useTheme } from "next-themes";
import Hero from "../components/Hero";

export default function Home() {

    const { theme, setTheme} = useTheme()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero />
            
        </>
    );
}
